Merchant repository respc
leehopper/black_thursday pull request #11
Opened 2021-06-03 22:23 UTC by chsweet

Type of Change:

- Refactor Merchant class
- Refactor MerchantRepository class and spec file

What does it implement:

- Updated Merchant class id variable to be and integer.
- Updated and refactored all tests for MerchantRepository class
- Refactored update method in MerchantRepository class to work

Any relevant logs, error outputs, etc.:

- All tests are passing

2021-06-03 23:36 UTC, leehopper requested changes
Looks great to me, one tiny requested change (just a variable typo) and one formatting suggestion.

2021-06-03 23:36 UTC, leehopper commented on spec/merchant_repository_spec.rb
> +        updated_all_merchants << merchant.name
I think this should be `updated_all  <<  merchant.name`, this is the only test that is failing for me and it looks like that is the issue.

2021-06-03 23:36 UTC, leehopper commented on lib/merchant_repository.rb
> +                                 name: attributes}, self)
Thoughts on making this one line? With only 2 items in the hash, the current formatting catches my eye. Not essential though. If the `next_highest_merchant_id` method name was condensed that could help with the one line formatting.

2021-06-04 17:01 UTC, marlitas reviewed
Just the on downcase to upcase thing. Everything else looks solid.

2021-06-04 17:01 UTC, marlitas commented on lib/merchant_repository.rb
>          merchant.name.downcase.include?name.downcase
Nit-picky but if we're sticking with upcase all around we should change this to upcase too.

2021-06-04 17:34 UTC, leehopper approved these changes

2021-06-04 17:34 UTC, merged